# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6a1bf496d6a5573e10dd12148eccfcb9f4fe6981cae1bbcd2cc288ac4db80279e1072c28ef36084564a7ec1fa40dbdfabfa79bf71320aa157b17c23eab1e8553

test:
  secret_key_base: f310166a3f9c17a434de59e221bfb6394d47ca2d40174ef883a37c8c23125d50922be8bcad535aaa4f4c9f9ddc1160cf602aeaff8694c1a72e426493637e2ab2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["IPEDS_SECRET"] %>
